In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [3]:
minihomeprices =pd.read_csv('minihomeprices.csv')

In [4]:
minihomeprices.head()

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         4   18  610000
3  3600         3   30  595000
4  4000         5    8  760000

In [5]:
minihomeprices.describe()

area  bedrooms        age          price
count     6.000000  6.000000   6.000000       6.000000
mean   3416.666667  4.166667  16.500000  648333.333333
std     587.934237  1.169045   8.288546  109117.673484
min    2600.000000  3.000000   8.000000  550000.000000
25%    3050.000000  3.250000   9.750000  572500.000000
50%    3400.000000  4.000000  16.500000  602500.000000
75%    3900.000000  4.750000  19.500000  722500.000000
max    4100.000000  6.000000  30.000000  810000.000000

In [6]:
features = minihomeprices.drop(columns =['bedrooms'])
target = minihomeprices['bedrooms']

In [7]:
print(features)
print(target)

   area  age   price
0  2600   20  550000
1  3000   15  565000
2  3200   18  610000
3  3600   30  595000
4  4000    8  760000
5  4100    8  810000
0    3
1    4
2    4
3    3
4    5
5    6
Name: bedrooms, dtype: int64


In [8]:
scaler = StandardScaler()

In [9]:
scaler.fit(features)

StandardScaler()

In [10]:
standardized_data = scaler.transform(features)

In [11]:
print(standardized_data)

[[-1.52162173  0.46257302 -0.98717986]
 [-0.77633762 -0.19824558 -0.8365931 ]
 [-0.40369556  0.19824558 -0.38483283]
 [ 0.34158855  1.78421022 -0.53541959]
 [ 1.08687266 -1.12339162  1.12103476]
 [ 1.27319369 -1.12339162  1.62299062]]


In [12]:
x_train,x_test,y_train,y_test = train_test_split(features,target,test_size = 0.2, random_state=2)

In [13]:
print(features.shape,x_train.shape,x_test.shape)

(6, 3) (4, 3) (2, 3)


In [14]:
classifier = LogisticRegression()

In [15]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [16]:
y_prediction = classifier.predict(x_train)
training_data_accuracy = accuracy_score(y_train,y_prediction)
print('Accuracy score of the training data:',training_data_accuracy)

Accuracy score of the training data: 1.0


In [17]:
y_prediction = classifier . predict(x_test)
training_data_accuracy = accuracy_score(y_test,y_prediction)
print('Accuracy score of the training data:',training_data_accuracy)

Accuracy score of the training data: 0.5


In [18]:
input_data = (0,45,50000)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)
if(prediction[0] == 0):
    print('The area is not specified minihomeprices')
else:
    print('The area is specified minihomeprices')

[[-6.36596846  3.76666602 -6.00673847]]
[3]
The area is specified minihomeprices
